* Org-Gcal [[http://melpa.org/#/org-gcal][file:http://melpa.org/packages/org-gcal-badge.svg]]
 =org-gcal= offers
  - Fetch google calendar event
  - Post/edit org element
  - Sync between Org and Gcal
    
* Requirements
 
- [[https://github.com/tkf/emacs-request][tkf/emacs-request]]
- [[https://github.com/jwiegley/alert][jwiegley/alert]]

  =org-gcal= is now available in the famous emacs package repo [[http://melpa.milkbox.net/][MELPA]], so the recommended way is to install it through Emacs package management system.

* Installation

1. Go to [[https://console.developers.google.com/project][Google Developers Console]]

2. Create a project (with any name)

3. Click on the project

4. Click on *Dashboard*

5. Click on *Library*

6. Choose *Google Calender API* and click *ENABLE*

7. Click on *OAuth Consent Screen*

8. Choose *Internal* and click *Create*

9. Choose any *App Name* and any Support and Developer E-Mail addresses -> *SAVE AND CONTINUE*

10. Add appropriate scopes for the Google Calender API (eg., only allow read access if you only want to fetch) -> *SAVE AND CONTINUE*

11. Click on *Credentials*

12. Click on *Create Credentials* -> *Create OAuth client ID*

13. Choose *Desktop App*, choose any name and click *Create*

14. Record the Client ID and Client secret for setup.

15. Go to [[https://www.google.com/calendar/render][Google setting page]] and click the gear-shaped settings icon in the upper right, then select "Settings" from the drop down list.

16. Select the calendar you would like to synchronize with in the left sub navigation.

17. Click on *Integrate Calendar*

18. Copy the Calendar ID for use in the settings below, where you will use it as the first element in the org-gcal-file-alist for associating calendars with specific org files. You can associate different calendars with different org files, so repeat this for each calendar you want to use.

** Setting example

#+begin_src elisp
(require 'org-gcal)
(setq org-gcal-client-id "your-id-foo.apps.googleusercontent.com"
      org-gcal-client-secret "your-secret"
      org-gcal-file-alist '(("your-mail@gmail.com" .  "~/schedule.org")
                            ("another-mail@gmail.com" .  "~/task.org")))
#+end_src


* Usage
** =org-gcal-sync=
   Sync between Org and Gcal. before syncing,  execute =org-gcal-fetch= .
** =org-gcal-fetch=
   Fetch Google calendar events and populate =org-gcal-file-alist= locations. The org files in =org-gcal-file-alist= should be blank or all of their headlines should have timestamps.
** =org-gcal-post-at-point=
   Post/edit org block at point to Google calendar.
** =org-gcal-delete-at-point=
   Delete Gcal event at point.
** =org-gcal-refresh-token=
   Refresh the OAuth token. OAuth token expired in 3600 seconds, You should refresh token on a regular basis.

* Similar application
  [[https://github.com/dengste/org-caldav][dengste/org-caldav]]
